### ISSUE TITLE
Error using fminunc (line 343)

### ISSUE THREAD

**Issue by karapish** [ceshine/RRL_Matlab#1]
Hi,

When I run testDAX.m or testTWSE.m in Matlab I'm getting an error 

**Error using fminunc (line 343)
FMINUNC requires all values returned by functions to be of data type double.**

**Error in testTWSE (line 35)
[theta, cost, EXITFLAG,OUTPUT] = fminunc(@(t)(costFunction(Xn(1:M+T), X(1:M+T), t)), initial_theta, options);**

Is this expected?

**Comment by ceshine** [comment]
Hi karapish,

I’m pleasantly surprised that this repo is still getting attention. Unfortunately I dropped this project years ago and rarely use Matlab since, so I'm not sure what's going on. My guess is that there are some changes in the fminunc API.
