### ISSUE TITLE
pdf file not found.

### ISSUE THREAD

**Issue by BrightFeather** [ceshine/RRL_Matlab#3]
pdf file not found. Could you upload to this repo? Thanks!

**Comment by Stranger2015** [comment]
[Molina-StockTradingWithRecurrentReinforcementLearning.pdf](https://github.com/ceshine/RRL_Matlab/files/1584577/Molina-StockTradingWithRecurrentReinforcementLearning.pdf)
@BrightFeather Is it what you're looking for?

**Comment by BrightFeather** [comment]
@Stranger2015 Yes, thanks!
