### ISSUE TITLE
A pair papers on rrl and rrn

### ISSUE THREAD

**Issue by Stranger2015** [ceshine/RRL_Matlab#4]
[Deep Recurrent Q-Learning for Partially Observable MDPs.pdf](https://github.com/ceshine/RRL_Matlab/files/1629664/Deep.Recurrent.Q-Learning.for.Partially.Observable.MDPs.pdf)
[1509.03044.A HYBRID APPROACH.pdf](https://github.com/ceshine/RRL_Matlab/files/1629666/1509.03044.A.HYBRID.APPROACH.pdf)
Don't be surprised )) I found two awesome articles and decided to upload to you.

**Comment by Stranger2015** [comment]
just to close

**Comment by ceshine** [comment]
Well, I'm surprised anyway. :) Sorry for the late reply.

I played a bit with DQN before, but DRQN is new to me. 

I'm wondering why people can still find this repo. Does RRL still of interest to you? Is there a lack of modern implementation of RRL? If so, re-implementing in Python might be a interesting project.

**Comment by Stranger2015** [comment]
DRQN : DQN+RECURRENT I guess? My  interest is in principle whole ML area. Initially i was within ICL.
So I'm currently a bit aside of RL.
I answered the question on StackExchange Cross validated https://stats.stackexchange.com/questions/57244/what-is-recurrent-reinforcement-learning/139720#139720 and found the yours ONLY. about
I did think about   re-implementation (JAVA), but it's the plans so far.

**Comment by ceshine** [comment]
Thanks for the reply. 

Yes, DRQN is the terminology used in the first paper. 

Interesting. This project was created before I started to get more serious about ML. I have also stopped using Matlab and switched to R and Python. I might review this topic in the near future and see how it has evolved over the years...
